# frontend/Dockerfile
FROM node:18-alpine

WORKDIR /usr/src/app

# Install Node.js dependencies
COPY package*.json ./
RUN npm install

# Copy the entire frontend source code
COPY . .

EXPOSE 3000

# Start the Next.js development server
CMD ["npm", "run", "dev"]
