repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.0
    hooks:
      - id: ruff
        # Use --fix so that auto‑fixes occur and point to the backend config.
        args: ["--fix", "--config", "backend/pyproject.toml"]
        # Only run on Python files under the backend folder.
        files: ^backend/.*\.py$

  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        # Check formatting using the configuration in backend/pyproject.toml.
        args: ["--check", "--verbose", "--config", "backend/pyproject.toml"]
        files: ^backend/.*\.py$
