version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: crewai_backend
    env_file: .env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    # The command here is optional if you rely on the CMD in the Dockerfilse.
    command: sh -c "python backend/manage.py migrate && python backend/manage.py runserver 0.0.0.0:8000"
    depends_on:
      - chromadb

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: crewai_frontend
    env_file: .env
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - backend

  chromadb:
    image: chromadb/chroma:0.3.22
    container_name: crewai_chromadb
    environment:
      CHROMA_DB_IMPL: disk
    volumes:
      - chroma-data:/app/chroma
    ports:
      - "8002:8002"

volumes:
  chroma-data:
