analyze_document:
  description: >
    Analyze a document's content to extract key insights and summarize its content.
  expected_output: >
    A detailed summary of the document, highlighting key points and insights.
  agent: document_analyzer

analyze_image:
  description: >
    Analyze an image by performing OCR and image recognition to generate a descriptive summary.
  expected_output: >
    A descriptive summary of the image content.
  agent: image_analyzer

web_search:
  description: >
    Perform a web search based on the provided query and summarize the findings.
  expected_output: >
    A summary of web search results and relevant information.
  agent: web_searcher

aggregate_information:
  description: >
    Combine the outputs from document analysis, image analysis, and web search into a comprehensive report.
  expected_output: >
    A consolidated report that integrates insights from the document, image, and web search.
  agent: document_analyzer
