research_task:
  description: >
    Perform an exhaustive online search on the provided query using AISearchTool.
    The Expert Web Researcher will leverage the Serper AI API to obtain live search result links and then use Jina Reader to extract clean content.
  expected_output: "A comprehensive set of initial research findings."
  agent: "web_researcher"
  async_execution: false
  output_file: "research_output.txt"

aggregate_task:
  description: >
    Analyze and consolidate the raw research data.
    The Analytical Aggregator will meticulously compile and organize the findings into a coherent summary that highlights key insights.
  expected_output: "A curated summary of the research findings."
  agent: "aggregator"
  context:
    - "research_task"
  async_execution: false
  output_file: "aggregate_output.txt"

synthesize_task:
  description: >
    Integrate the aggregated insights into a final, comprehensive answer.
    The Innovative Synthesizer will transform the curated summary into an articulate and actionable response.
  expected_output: "Final Answer: <comprehensive, detailed response>"
  agent: "synthesizer"
  context:
    - "aggregate_task"
  async_execution: false
  output_file: "synthesize_output.txt"
