research_task:
  description: >
    Perform an exhaustive online search on the provided query using AISearchTool.
    The Expert Web Researcher will leverage the Serper AI API to obtain live search result links and then use Jina Reader to extract clean content.
  expected_output: "A comprehensive set of initial research findings."
  agent: "web_researcher"
  async_execution: false
  output_file: "research_output.txt"

aggregate_task:
  description: >
    Analyze and consolidate the raw research data.
    The Analytical Aggregator will compile and organize the findings into a coherent summary that highlights key insights.
  expected_output: "A curated summary of the research findings in **Markdown** format."
  agent: "aggregator"
  context:
    - "research_task"
  async_execution: false
  output_file: "aggregate_output.txt"

store_task:
  description: >
    Store the aggregated research summary into the persistent Chroma vector store.
  expected_output: "Text stored successfully"
  agent: "aggregator"
  context:
    - "aggregate_task"
  async_execution: false
  output_file: "stored_output.txt"

synthesize_task:
  description: >
    Integrate the aggregated insights into a final, comprehensive, and actionable answer.
  expected_output: "Final synthesized answer in **Markdown** format."
  agent: "synthesizer"
  context:
    - "aggregate_task"
  async_execution: false
  output_file: "synthesize_output.txt"
