name: Python checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
        working-directory: backend

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
        working-directory: backend

      - name: Lint with ruff
        run: ruff check .
        working-directory: backend

      - name: Check formatting with Black
        run: black . --check --verbose
        working-directory: backend

      - name: Run unit tests
        run: pytest
        working-directory: backend
