name: Python checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ../requirements-dev.txt

      - name: Lint with ruff
        run: |
          # Check for severe issues first
          ruff . --select=E9,F63,F7,F82
          # Then run full linting (exit-zero to treat warnings as warnings)
          ruff . --exit-zero

      - name: Check formatting with Black
        uses: psf/black@stable
        with:
          src: "."
          options: "--check --verbose --config=pyproject.toml"

      - name: Run unit tests
        run: pytest
